---
title: "Lab1 Yuchen Wang"
output: html_document
---
```{r}
setwd("C:/Users/63139/treasure/studying/585/Lab1")
library(tidyverse)
library(ggplot2)
library(readr)
library(ggmap)
library(maps)
library(mapdata)
weather <- read_fwf("ushcn-v2.5-stations.txt", 
                    fwf_positions(c(1,3,4,6,13,22,33,39,42,94),c(2,3,5,11,20,30,37,40,71,95), 
                    col_names=c("COUNTRY","NETWORK","ID_PLACEHOLDERS","COOP_ID","LATITUDE","LONGITUDE","ELEVATION","STATE","NAME","TimeZone")),
                    col_types = cols("c","c","c","c",
                                     "d","d","d",
                                     "c","c","i")
                    )
head(weather)

```

Set TimeZone as a factor and rename the levels in TimeZone
```{r}
weather$TimeZone <- as.factor(weather$TimeZone)
levels(weather$TimeZone) = c("ETS", "CTS","MTS","PTS")
```


Plot the map with the data
```{r}
states <- map_data("state")
ggplot(data = states) + 
  geom_polygon(aes(x = long, y = lat, fill = region, group = group), color = "white",alpha = 0.4) + 
  coord_fixed(1.3) +
  guides(fill=FALSE)+
  geom_point(data=weather,aes(x=LONGITUDE,y=LATITUDE,color=(ELEVATION),shape=TimeZone))

```

Unzip the file
```{r}
#gunzip("ushcn.tavg.latest.raw.tar.gz")
#untar("ushcn.tavg.latest.raw.tar")
```

Count the number of files
```{r}
length(list.files("C:/Users/63139/treasure/studying/585/Lab1/ushcn.v2.5.5.20190130"))
```

The coordinate of Fort Dodge, IA is (42.506803, ???94.180271). Search the weather data for this cordinate.
```{r}
select<- weather %>% 
  filter(LATITUDE>42 & LATITUDE<43 & LONGITUDE< -94 & LONGITUDE> -95)
select
paste(select$COUNTRY[1],select$NETWORK[1],select$ID_PLACEHOLDERS[1],select$COOP_ID[1],".raw.tavg",sep="")
```

